Rename eof() as s_eof() to avoid conflicts with mingw-w64 eof()
Fixes
error: conflicting types for ‘eof’

Signed-off-by: Marko Lindqvist <cazfi74@gmail.com>